[Build]
    command = "npm run prod"
    publish = "dist"
    functions = ""


[[plugins]]
    package = "netlify-plugin-csp-headers"

# https://medium.com/@brandonl.4231/how-i-increased-the-security-of-my-netlify-hosted-website-with-this-one-small-trick-731f4c56efd7
[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        Referrer-Policy = "no-referrer"
        X-Content-Type-Options = "nosniff"


# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200