[Build]
    command = "npm run prod"
    publish = "dist"
    functions = ""



[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self';"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        Referrer-Policy = "no-referrer"
        X-Content-Type-Options: "nosniff"


# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200