[Build]
    command = "npm run prod"
    publish = "dist"
    functions = ""


[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self';"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200